
# Text for the article

tool:
  pre:
    - >
      As Machine Learning (ML) models are increasingly used to inform high-stake
      decisions, such as loan approvals and school admissions, there has been a
      surge of interest in the field of algorithmic recourse—designing
      techniques that suggest actions to alter the outcomes of ML models. In a
      loan application scenario, a recourse plan that alters a loan rejection
      decision can have the form of "if you increase your annual income by $5k,
      you will get the loan." GAM Coach is a web-based interactive tool that
      <strong>empower end-users to iteratively discover recourse plans that meet
      their preferences.</strong>
    - >
      Existing recourse generation techniques have the implicit assumption that
      ML developers understand what input variables can be changed and how
      difficult it is to change them. However, the actionability of a recourse
      plan is ultimately subjective and personal, and unlikely to match
      developers' expectations completely. To bridge this mismatch, GAM Coach
      <strong>enable end-users to easily specify recourse preferences</strong>,
      such as the <em>difficulty</em> and <em>acceptable range</em> of a
      feature, and <strong>iteratively fine-tune recourse plans</strong> until
      finding satisfactory ones.

feature:
  main: >
    Please watch a walk-through tutorial video below to learn how a loan
    applicant can use GAM Coach.
  gap: >
    If you encounter any problems while using GAM Coach, you can click the link
    below to watch a shorter and more specific video explaining how each GAM
    Coach functionality works. You can also <a
    href="mailto:jayw@gatech.edu">email us</a>.
  list:
    - name: Change initial input values
      id: input
    - name: Explore different strategies to get a loan approval
      id: explore
    - name: >
        Experiment with different feature values to see how they affect the
        application decision
      id: value
    - name: Specify difficulty of different features
      id: difficulty
    - name: Specify the acceptable range of different features
      id: range
    - name: Generate new strategies that meet your preferences
      id: generate
    - name: Set the max number of features that plans can change
      id: max-num
    - name: Bookmark strategies you like and download a "receipt"
      id: download
    - name: Submit the HIT task
      id: submit

video:
  - header: Change initial input values
    video: input
    isWide: true
    text: >
      The default GAM Coach input is based on the information from a real
      rejected loan applicant. The initial values might be very different from
      your values. If it can help you imagine being a real user using GAM Coach,
      you can change the input values to mimic your values or someone you know.
  - header: Explore different strategies
    video: explore
    isWide: false
    text: >
      Every time you ask GAM Coach to generate strategies, it generates 5
      different plans for you. You can click the different tabs to compare and
      explore different plans. If you set some configurations to some feature
      under one tab, the configuration is synced to all other tabs
      automatically. <strong>You need to click the regenerate button to apply these new
      configurations.</strong>
  - header: Change feature values
    video: value
    isWide: false
    text: >
      You might want to try out some "hypothetical" values to see how the they
      would affect your loan decision score. Setting these values does not have
      any impact on you or new plan generations.
  - header: Specify difficulty
    video: difficulty
    isWide: false
    text: >
      GAM Coach tries to find the "best" strategy for users to succeed. However,
      the definition of "best" is different from one user to another. For
      example, maybe it is easier for you to change <code>FICO score</code> in
      real life, but it might be easier for your friend to change <code>Loan
      Amount</code> instead. Therefore, GAM Coach allows you to specify the
      difficulty to change a feature in real life. New plans will try to
      prioritize features that are easier for you to change and ignore features
      that are hard or impossible to change.
  - header: Specify acceptable range
    video: range
    isWide: false
    text: >
      Similar to difficulties, many users have an "acceptable range" of changes.
      For example, some user might be able to lower the <code>Loan Amount</code>
      in the next application, but they can only decrease it by $2000. They can
      tell GAM Coach the acceptable range by dragging sliders or clicking bars
      in the feature cards. New plans will make sure to meet your acceptable
      range.
  - header: Generate new strategies
    video: generate
    isWide: false
    text: >
      After setting difficulties and acceptable ranges for some features, you
      can click the "Regenerate" button to generate new plans that meet your
      constraints. You can keep fine-tuning your specifications and regenerating
      new plans until you find the strategies that work <strong>for
      you</strong>.
  - header: Max number of features that a plan can change
    video: max-num
    isWide: false
    text: >
      Some users prefer strategies that only change a few features. You can change
      the max number of features that a plan can change by clicking the drop
      down menu on the top right of the tool.
  - header: Bookmark strategies and download a receipt
    video: download
    isWide: false
    text: >
      Don't forget to save plans you like by clicking the star icon in the tab
      bar. It would save the plan to your Bookmarks. In the Bookmarks pop-up,
      You can also download a receipt. A receipt is a securely signed document
      that you can use as proof in your future applications: if you make the
      changes suggested by GAM Coach, the bank will guarantee you a loan
      approval.
  - header: Submit the HIT task
    video: submit
    isWide: true
    text: >
      After you find your favorite strategies, you can click the "I'm Done"
      button to submit. It would ask you to rate your preferences and plans.
      Please provide detailed explanations. Next, GAM Coach will show you a
      unique 6-digit verification code. You need to copy the code in the Google
      Survey and the HIT page.

