
# Text for the article

introduction:
  main:
    - >
      👋 Hello! We are a team of computer science researchers. Thank you so much
      for taking your time to help us improve our tool, GAM Coach.
    - >
      You might have heard that some banks 🏦 are using Artificial Intelligence
      (AI) to decide whether a person can or cannot get a loan. These banks ask
      for the loan applicant's information, such as <u>annual income</u>,
      <u>employment length</u>, and <u>credit score</u>. Then, the banks use AI
      programs to go through all collected information and decide on whether to
      approve or reject this client's loan application.
    - >
      Unfortunately, many people's loan applications are rejected by these
      programs. 🙁 Therefore, we are developing GAM Coach, an interactive
      coaching tool to <strong>help these rejected loan applicants succeed in
      their future applications!</strong> 💪 To do that, GAM Coach identifies an
      applicant's current weakness and provides simple and customizable
      strategies to get their next loan application approved.
    - >
      In this task, we want you to <strong>pretend to be a person whose loan
      application is rejected by a bank</strong>. The bank points you to GAM
      Coach to help you improve and succeed in future applications.
  important:
    - >
      Please try your best to imagine that you are a real user—using GAM Coach
      to find the strategies that <strong>you think are useful</strong>. Our
      goal in this study is to learn what strategies would be helpful for real
      users and how GAM Coach can help.

tool:
  pre:
    - >
      GAM Coach is a web-based interactive tool that helps users identify
      strategies to obtain a desirable AI decision (e.g., loan application
      approval). These strategies can be "if you increase your FICO score
      (credit score) by 3 points, and increase your credit utilization by 2.65%,
      you will get the loan." (figure below)
  after:
    - >
      In this scenario, you are a loan applicant whose application is rejected
      by a bank. The bank then gives you a link to GAM Coach to help you improve
      and succeed in the next application. GAM Coach is pre-loaded with all
      "information" you provided to the bank, e.g., <code>annual income</code>,
      <code>employment length</code>, <code>FICO score</code> (credit score).
      Each piece of the information is called a "feature". For example,
      <code>FICO score</code> is one feature, and it has your value
      <code>650</code>.
    - >
      GAM Coach uses all these features and values to compute best strategies
      that you can apply to get the next loan. In addition, you can tell GAM
      Coach what features are easier to change than others. For example, maybe
      it's easier for you to change your <code>FICO score</code> than changing
      <code>employment length</code>, and maybe you only want to change
      <code>FICO Score</code> in a certain range. As you can see, these strategy
      preferences vary from user to user, so GAM Coach allows you to specify
      <strong>your own preference</strong> and generate personalized strategies
      <strong>just for you.</strong>

feature:
  main: >
    Please watch a walk-through tutorial video below to learn how a loan
    applicant can use GAM Coach.
  gap: >
    If you encounter any problems while using GAM Coach, you can click the link
    below to watch a shorter and more specific video explaining how each GAM
    Coach functionality works.
  list:
    - name: Change initial input values
      id: s-input
    - name: Explore different strategies to get a loan approval
      id: s-explore
    - name: >
        Experiment with different feature values to see how they affect
        the application decision
      id: s-value
    - name: Specify difficulty of different features
      id: s-difficulty
    - name: Specify the acceptable range of different features
      id: s-range
    - name: Generate new strategies that meet your preferences
      id: s-generate
    - name: Bookmark strategies you like and download a "receipt"
      id: s-download
    - name: Submit the HIT task
      id: s-submit

task:
  main: >
    The main task in this HIT is to <strong>pretend to be a real user</strong>
    and use GAM Coach until you find a strategy (or strategies) that you are
    satisfied with. The strategy can be anything. It can be one of the first
    five initial strategies, or a follow-up strategy that meets your specified
    preference. <strong>There is no right answer</strong>, just use GAM Coach as
    you are a real loan applicant who hopes to find a good strategy to improve.
    😄
  gap: >
    Here are some concrete steps to help you complete the HIT:
  list:
    - >
      <strong>Click the edit icon</strong> on the left panel to
      change the initial input values. For example, you can change the input to
      match someone you know, so the scenario is more <strong>relatable to
      you</strong>.
    - >
      <strong>Imagine to be a real user</strong> and use GAM Coach
    - >
      <strong>Click the the star icon</strong> on the plan tabs to bookmark
      strategies you like
    - >
      Once you are satisfied with your bookmarked strategies (one or several),
      <strong>click the "I'm done" button</strong> on the right panel
    - >
      <strong>Rate</strong> your bookmarked strategies and
      <strong>explain</strong> why you like them
    - >
      <strong>Click the "submit" button</strong> to submit the data to us. The
      data contains your interaction logs (e.g., clicks, hovering, drags) and
      all generated strategies.
    - >
      GAM Coach will generates a unique code (6-digit number) for you,
      <strong>copy and paste</strong> it in your google survey
    - >
      <strong>Answer all questions</strong> in the Google survey and
      <strong>submit</strong> the survey
    - >
      <strong>Paste the code</strong> in MTurk page and <strong>submit</strong>
      it
    - >
      Done—thank you so much! 🙏
  accept: >
    We will accept your HIT once (1) we have received your interaction log and strategy
    data, Google survey, HIT submission under the <strong> same
    verification code</strong>, (2) the interaction log data and survey
    response suggest that you have <strong>made effort to pretend to be a real
    user</strong> using GAM Coach. For example, the survey responses are
    coherent with your interactions with the tool.

overview: >
  The tutorial video above will help you learn how to use GAM Coach and complete
  this HIT. Please don't replicate what the video does. We want you to imagine to
  be a real user and use GAM Coach to find strategies <strong>work for
  you.</strong>

detail: >
  We list a few more shorter videos that each explain one functionality of GAM
  Coach. You are not required to watch these videos. However, if you encounter
  any problems while using GAM Coach, you might find these videos helpful.

video:
  - header: Change initial input values
    video: input
    isWide: true
    text: >
      We highly recommend you to watch this overview video. It shows how a crowd
      work pretends to be a loan applicant and uses GAM Coach to find good
      strategies to help future applications.
  - header: Explore different strategies
    video: explore
    isWide: false
    text: >
      The default GAM Coach input is based on the information from a real
      rejected loan applicant. The initial values might be very different from
      your values. If it can help you imagine being a real user using GAM Coach,
      you can change the input values to mimic your values or someone you know.
      This step is optional.
  - header: Change feature values
    video: value
    isWide: false
    text: >
      Every time you ask GAM Coach to generate strategies, it generates 5
      different plans for you. You can click the different tabs to compare and
      explore different plans. If you set some configurations to some feature
      under one tab, the configuration is synced to all other tabs
      automatically.
  - header: Specify difficulty
    video: difficulty
    isWide: false
    text: >
      GAM Coach tries to find the "best" strategy for users to succeed. However,
      the definition of "best" is different from one user to another. For
      example, maybe it is easier for you to change <code>FICO score</code> in
      real life, but it might be easier for your friend to change <code>Loan
      Amount</code> instead. Therefore, GAM Coach allows you to specify the
      difficulty to change a feature in real life. New plans will try to
      prioritize features that are easier for you to change and ignore features
      that are hard or impossible to change.
  - header: Specify acceptable range
    video: range
    isWide: false
    text: >
      Similar to difficulties, many users have an "acceptable range" of changes.
      For example, some user might be able to lower the <code>Loan Amount</code>
      in the next application, but they can only decrease it by $2000. They can
      tell GAM Coach the acceptable range by dragging sliders or clicking bars
      in the feature cards. New plans will make sure to meet your acceptable
      range.
  - header: Generate new strategies
    video: generate
    isWide: false
    text: >
      After setting difficulties and acceptable ranges for some features, you
      can click the "Regenerate" button to generate new plans that meet your
      constraints. You can keep fine-tuning your specifications and regenerating
      new plans until you find the strategies that work <strong>for
      you</strong>.
  - header: Bookmark strategies and download a receipt
    video: download
    isWide: false
    text: >
      Don't forget to save plans you like by clicking the star icon in the tab
      bar. It would save the plan to your Bookmarks. In the Bookmarks pop-up,
      You can also download a receipt. A receipt is a securely signed document
      that you can use as proof in your future applications: if you make the
      changes suggested by GAM Coach, the bank will guarantee you a loan
      approval.
  - header: Submit the HIT task
    video: submit
    isWide: true
    text: >
      After you find your favorite strategies, you can click the "I'm Done"
      button to submit. It would ask you to rate your saved plans. Please write
      a few sentences describing why you choose these strategies and rate them.
      Next, GAM Coach will show you a unique 6-digit verification code. You want
      to put the code in the Google Survey as well as the HIT page.

