name: build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #: Run the test every week
  schedule:
    - cron: "0 12 * * 1"

jobs:
  python-library:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.7']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Run python tests
      run: pytest

  ui:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./gamcoach-ui

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16]

    steps:
    - uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm dependencies
      working-directory: ./gamcoach-ui
      run: npm install
    - name: Build UI
      working-directory: ./gamcoach-ui
      run: npm run build